### ISSUE TITLE
chatbot for effective UX

### ISSUE THREAD

**Issue by deekay2310** [deekay2310/calorieApp_server#49]
[DialogFlow](https://cloud.google.com/dialogflow/docs) provides some great solutions to develop and deploy the chatbot

**Comment by SunidhiHegde** [comment]
Customized built-in [small talk](https://cloud.google.com/dialogflow/es/docs/agents-small-talk) functionality to enable casual conversation. Potential questions from the user and relevant responses from the bot added.

**Comment by deekay2310** [comment]
chatbot has been deployed
